/// <reference path="../keyboard.ts" />

namespace Keyboard {
  defineKeyboard({
    name: "<b>PHN</b>",
    code: "PHN",
    description: "Phönizisch\nPhönizisch-Punisch",
    version: "2018.04.25",
    imports: ["https://fonts.googleapis.com/earlyaccess/notosansphoenician.css"],
    style: 'keyboard{font-family:"Noto Sans","Noto Sans Phoenician",Calibri,Roboto,Arial,sans-serif;}',
    keyMap: {
      AltLeft: ["Alt", "Alt"],
      Backspace: ["\u27f5", "Backspace"],
      Comma: "𐤕",
      ControlLeft: ["Strg", "Control"],
      //      Digit0: "",
      Digit1: "𐤖",
      Digit2: "𐤚",
      Digit3: "𐤛",
      Digit5: "𐤗",
      Digit6: "𐤘",
      //      Digit7: "",
      Digit8: "𐤙",
      //      Digit9: "",
      Enter: ["\u21b2", "Enter"],
      KeyA: "𐤔",
      KeyB: "𐤍",
      KeyC: "𐤁",
      KeyD: "𐤂",
      KeyE: "𐤒",
      KeyF: "𐤊",
      KeyG: "𐤏",
      KeyH: "𐤉",
      //      KeyI: "",
      KeyJ: "𐤇",
      KeyK: "𐤋",
      //      KeyL: "",
      KeyM: "𐤑",
      KeyN: "𐤌",
      //      KeyO: "",
      KeyP: "𐤐",
      KeyR: "𐤓",
      KeyS: "𐤃",
      KeyT: "𐤀",
      KeyU: "𐤅",
      KeyV: "𐤄",
      //      KeyW: "",
      KeyX: "𐤎",
      KeyY: "𐤆",
      KeyZ: "𐤈",
      Language: ["PHN", "Language"],
      //      Minus: "",
      //      Period: "",
      //      Quote: "",
      //      Semicolon: "",
      //      Slash: "",
      WordSeparator: "𐤟",
      Space: ["\u23b5", "Space"]
    },
    layout: [
      "Digit1", "Digit2", "Digit3", "Digit4", "Digit5", "Digit6", "Digit7", "Digit8", "Digit9", "Digit0",
      "KeyW", "Minus", "KeyE", "KeyR", "KeyT", "KeyY", "KeyU", "KeyI", "KeyO", "KeyP",
      "KeyA", "KeyS", "KeyD", "KeyF", "KeyG", "KeyH", "KeyJ", "KeyK", "KeyL", "Semicolon",
      "KeyZ", "KeyX", "KeyC", "KeyV", "KeyB", "KeyN", "KeyM", "Comma", "Period", "#Backspace",
      "#Language:3", "#ControlLeft", "#Space:5", "#WordSeparator:5", "#AltLeft", "#Enter:3"
    ]
  });
}
