/// <reference path="../keyboard.ts" />
var Keyboard;
(function (Keyboard) {
    Keyboard.defineKeyboard({
        name: "<b>ΕΛ</b>",
        code: "GRE",
        description: "Griechisch\nGriechisch (Politonisch)",
        version: "2018.04.25",
        keyMaps: {
            shift: {
                AltLeft: ["Alt", "Alt"],
                Backspace: ["\u27f5", "Backspace"],
                Comma: "<",
                ControlLeft: ["Strg", "Control"],
                Digit0: ")",
                Digit1: "!",
                Digit2: "@",
                Digit3: "#",
                Digit4: "$",
                Digit5: "%",
                Digit6: "^",
                Digit7: "&",
                Digit8: "*",
                Digit9: "(",
                Enter: ["\u21b2", "Enter"],
                KeyA: "Α",
                KeyB: "Β",
                KeyC: "Ψ",
                KeyD: "Δ",
                KeyE: "Ε",
                KeyF: "Φ",
                KeyG: "Γ",
                KeyH: "Η",
                KeyI: "Ι",
                KeyJ: "Ξ",
                KeyK: "Κ",
                KeyL: "Λ",
                KeyM: "Μ",
                KeyN: "Ν",
                KeyO: "Ο",
                KeyP: "Π",
                KeyQ: ";",
                KeyR: "Ρ",
                KeyS: "Σ",
                KeyT: "Τ",
                KeyU: "Θ",
                KeyV: "Ω",
                KeyW: "ς",
                KeyX: "Χ",
                KeyY: "Ζ",
                KeyZ: "Υ",
                Language: ["ΕΛ", "Language"],
                Period: ">",
                ShiftLeft: ["\u21d1", "Shift"],
                Space: ["\u23b5", "Space"]
            },
            ctrlAlt: {
                AltLeft: ["Alt", "Alt"],
                Backspace: ["\u27f5", "Backspace"],
                Comma: "«",
                ControlLeft: ["Strg", "Control"],
                Digit0: "°",
                Digit1: "Ϛ",
                Digit2: "Ϟ",
                Digit3: "Ϡ",
                Digit4: "£",
                Digit5: "§",
                Digit6: "¶",
                Digit7: "~",
                Digit8: "¤",
                Digit9: "¦",
                Enter: ["\u21b2", "Enter"],
                KeyA: "{",
                KeyB: "?",
                KeyC: "©",
                KeyD: "]",
                KeyE: "€",
                KeyF: "}",
                KeyG: "\\",
                KeyH: "|",
                KeyI: "ι",
                KeyJ: "/",
                // KeyK: "",
                // KeyL: "",
                // KeyM: "",
                // KeyN: "",
                // KeyO: "",
                // KeyP: "",
                KeyQ: "´",
                KeyR: "®",
                KeyS: "[",
                KeyT: "+",
                KeyU: "±",
                // KeyV: "",
                // KeyW: "",
                // KeyX: "",
                KeyY: "-",
                KeyZ: "¥",
                Language: ["ΕΛ", "Language"],
                Period: "",
                ShiftLeft: ["\u21d1", "Shift"],
                Space: ["\u23b5", "Space"]
            },
            shiftCtrlAlt: {
                AltLeft: ["Alt", "Alt"],
                Backspace: ["\u27f5", "Backspace"],
                // Comma: "",
                ControlLeft: ["Strg", "Control"],
                // Digit0: "",
                // Digit1: "",
                Digit2: "²",
                Digit3: "³",
                // Digit4: "",
                // Digit5: "",
                // Digit6: "",
                // Digit7: "",
                // Digit8: "",
                // Digit9: "",
                Enter: ["\u21b2", "Enter"],
                // KeyA: "",
                // KeyB: "",
                // KeyC: "",
                // KeyD: "",
                // KeyE: "",
                // KeyF: "",
                // KeyG: "",
                // KeyH: "",
                // KeyI: "",
                // KeyJ: "",
                // KeyK: "",
                // KeyL: "",
                // KeyM: "",
                // KeyN: "",
                // KeyO: "",
                // KeyP: "",
                // KeyQ: "",
                // KeyR: "",
                // KeyS: "",
                // KeyT: "",
                // KeyU: "",
                // KeyV: "",
                // KeyW: "",
                // KeyX: "",
                // KeyY: "",
                // KeyZ: "",
                Language: ["ΕΛ", "Language"],
                // Period: "",
                ShiftLeft: ["\u21d1", "Shift"],
                Space: ["\u23b5", "Space"]
            }
        },
        keyMap: {
            AltLeft: ["Alt", "Alt"],
            Backspace: ["\u27f5", "Backspace"],
            Comma: ",",
            ControlLeft: ["Strg", "Control"],
            Digit0: "0",
            Digit1: "1",
            Digit2: "2",
            Digit3: "3",
            Digit4: "4",
            Digit5: "5",
            Digit6: "6",
            Digit7: "7",
            Digit8: "8",
            Digit9: "9",
            Enter: ["\u21b2", "Enter"],
            KeyA: "α",
            KeyB: "β",
            KeyC: "ψ",
            KeyD: "δ",
            KeyE: "ε",
            KeyF: "φ",
            KeyG: "γ",
            KeyH: "η",
            KeyI: "ι",
            KeyJ: "ξ",
            KeyK: "κ",
            KeyL: "λ",
            KeyM: "μ",
            KeyN: "ν",
            KeyO: "ο",
            KeyP: "π",
            KeyQ: ";",
            KeyR: "ρ",
            KeyS: "σ",
            KeyT: "τ",
            KeyU: "θ",
            KeyV: "ω",
            KeyW: "ς",
            KeyX: "χ",
            KeyY: "ζ",
            KeyZ: "υ",
            Language: ["ΕΛ", "Language"],
            Period: ".",
            ShiftLeft: ["\u21d1", "Shift"],
            Space: ["\u23b5", "Space"]
        },
        layout: [
            "Digit1", "Digit2", "Digit3", "Digit4", "Digit5", "Digit6", "Digit7", "Digit8", "Digit9", "Digit0",
            "KeyQ", "KeyW", "KeyE", "KeyR", "KeyT", "KeyY", "KeyU", "KeyI", "KeyO", "KeyP",
            null, "KeyA", "KeyS", "KeyD", "KeyF", "KeyG", "KeyH", "KeyJ", "KeyK", "KeyL", null,
            "#ShiftLeft", "KeyZ", "KeyX", "KeyC", "KeyV", "KeyB", "KeyN", "KeyM", "#Backspace:4",
            "#Language:3", "#ControlLeft", "Comma", "#Space:6", "Period", "#AltLeft", "#Enter:3"
        ],
        getKeyMap: function () {
            if (Keyboard.hasFlag(this.modifiers, Keyboard.MODIFIER_SHIFT | Keyboard.MODIFIER_CTRL | Keyboard.MODIFIER_ALT) == (Keyboard.MODIFIER_SHIFT | Keyboard.MODIFIER_CTRL | Keyboard.MODIFIER_ALT)) {
                return this.keyMaps.shiftCtrlAlt;
            }
            else if (Keyboard.hasFlag(this.modifiers, Keyboard.MODIFIER_CTRL | Keyboard.MODIFIER_ALT) == (Keyboard.MODIFIER_CTRL | Keyboard.MODIFIER_ALT)) {
                return this.keyMaps.ctrlAlt;
            }
            else if (Keyboard.hasFlag(this.modifiers, Keyboard.MODIFIER_SHIFT) == Keyboard.MODIFIER_SHIFT) {
                return this.keyMaps.shift;
            }
            else {
                return this.keyMap;
            }
        },
        keyBindings: []
    });
})(Keyboard || (Keyboard = {}));
//# sourceMappingURL=GRE.js.map